# Code Generated by Sidekick is for learning and experimentation purposes only.
provider "aws" {
  region = "us-east-1"
}

resource "aws_s3_bucket" "example" {
  bucket = "rebuild-publish-doc-image-buc" # Change this!
  force_destroy = true
  tags = {
    Name = "ExampleBucket"
  }
}

output "bucket_name" {
  value = aws_s3_bucket.example.bucket
}
