# Code Generated by Sidekick is for learning and experimentation purposes only.
from flask import Flask
import os

app = Flask(__name__)

@app.route("/")
def home():
    return f"Hello! DB URL: {os.getenv('DATABASE_URL', 'not set')}"

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
